"""empty message

Revision ID: 25ac8296490a
Revises: 5025c353be23
Create Date: 2021-02-25 07:24:38.295626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ac8296490a'
down_revision = '5025c353be23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
