"""empty message

Revision ID: 3229f2500be8
Revises: 67f81384a20e
Create Date: 2021-02-28 04:35:15.525819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3229f2500be8'
down_revision = '67f81384a20e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kanji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcription', sa.UnicodeText(), nullable=True),
    sa.Column('cyrillic', sa.UnicodeText(), nullable=True),
    sa.Column('original_appearance', sa.UnicodeText(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_appearance')
    )
    op.create_table('meaning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association',
    sa.Column('kanji_id', sa.Integer(), nullable=True),
    sa.Column('meaning_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kanji_id'], ['kanji.id'], ),
    sa.ForeignKeyConstraint(['meaning_id'], ['meaning.id'], )
    )
    op.create_table('jap_reading_assoc',
    sa.Column('kanji_id', sa.Integer(), nullable=True),
    sa.Column('reading_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kanji_id'], ['kanji.id'], ),
    sa.ForeignKeyConstraint(['reading_id'], ['reading.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jap_reading_assoc')
    op.drop_table('association')
    op.drop_table('reading')
    op.drop_table('meaning')
    op.drop_table('kanji')
    # ### end Alembic commands ###
