"""empty message

Revision ID: 5025c353be23
Revises: 68b901928bf7
Create Date: 2021-02-25 06:18:42.419693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5025c353be23'
down_revision = '68b901928bf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
