"""empty message

Revision ID: 5288456ef5f4
Revises: 5b7128b86839
Create Date: 2021-02-25 07:38:09.012913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5288456ef5f4'
down_revision = '5b7128b86839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hiragana_cards', sa.Column('cyrillic', sa.Unicode(length=50), nullable=True))
    op.add_column('hiragana_cards', sa.Column('transcription', sa.Unicode(length=50), nullable=True))
    op.add_column('katakana_cards', sa.Column('cyrillic', sa.Unicode(length=50), nullable=True))
    op.add_column('katakana_cards', sa.Column('transcription', sa.Unicode(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('katakana_cards', 'transcription')
    op.drop_column('katakana_cards', 'cyrillic')
    op.drop_column('hiragana_cards', 'transcription')
    op.drop_column('hiragana_cards', 'cyrillic')
    # ### end Alembic commands ###
