"""empty message

Revision ID: 5b7128b86839
Revises: ef98a452a469
Create Date: 2021-02-25 07:35:26.698684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7128b86839'
down_revision = 'ef98a452a469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
