"""empty message

Revision ID: 68b901928bf7
Revises: be712912a75c
Create Date: 2021-02-25 06:04:17.283802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b901928bf7'
down_revision = 'be712912a75c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hiragana_cards', sa.Column('original_appearance', sa.Unicode(length=1), nullable=True))
    op.create_unique_constraint(None, 'hiragana_cards', ['original_appearance'])
    op.add_column('katakana_cards', sa.Column('original_appearance', sa.Unicode(length=1), nullable=True))
    op.create_unique_constraint(None, 'katakana_cards', ['original_appearance'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'katakana_cards', type_='unique')
    op.drop_column('katakana_cards', 'original_appearance')
    op.drop_constraint(None, 'hiragana_cards', type_='unique')
    op.drop_column('hiragana_cards', 'original_appearance')
    # ### end Alembic commands ###
