"""empty message

Revision ID: be712912a75c
Revises: 8572a578096b
Create Date: 2021-02-25 04:52:42.715484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be712912a75c'
down_revision = '8572a578096b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('katakana_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('katakana_cards')
    # ### end Alembic commands ###
