"""empty message

Revision ID: ef98a452a469
Revises: 25ac8296490a
Create Date: 2021-02-25 07:27:24.743682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef98a452a469'
down_revision = '25ac8296490a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
